server:
  port: 9393

spring:
  banner:
    location: static/banner.txt
  data:
    mongodb:
      database: masterReviews
      port: 27017
      host: localhost
  #servlet:
    #multipart:
      #enable: true
      #file-size-threshold: 2MB
     # max-file-size: 200MB
     # max-request-size: 215MB

app:
  display:
    uploadColumnNames:
      - review
      - reviewRating
      - ratingMaxValue
      - reviewDateCreated
      - reviewSupportImage
      - reviewUrl
      - reviewSource
      - reviewerName
      - reviewerLocation
      - reviewerEmail
      - reviewerContactNumber